# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports = [
    inputs.hardware.nixosModules.common-cpu-intel-cpu-only
    inputs.hardware.nixosModules.common-pc-ssd
    inputs.hardware.nixosModules.common-gpu-amd
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    # Valve says:
    #
    # We set amdgpu.lockup_timeout in order to control the TDR for each ring
    # 0 (GFX): 5s (was 10s)
    # 1 (Compute): 10s (was 60s wtf)
    # 2 (SDMA): 10s (was 10s)
    # 3 (Video): 5s (was 10s)

    # ttm.pages_min is set to 8GB in units of page size (4096), which is min
    # required for decent gaming performance.
    # amdgpu.sched_hw_submission is set to 4 to avoid bubbles of lack-of work
    # with the default (2).
    # 4 is the maximum that is supported across RDNA2 + RDNA3.
    # Any more results in a hang at startup on RDNA3.
    "log_buf_len=4M"
    "amd_iommu=off"
    "amdgpu.lockup_timeout=5000,10000,10000,5000"
    "ttm.pages_min=2097152"
    "amdgpu.sched_hw_submission=4"
    "audit=0"

    # These are mine so we can get a nice splash screen thing going
    "quiet"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a56fc09d-586c-4447-8373-6e623ed9265f";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3F49-310F"
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a56fc09d-586c-4447-8373-6e623ed9265f";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a56fc09d-586c-4447-8373-6e623ed9265f";
      fsType = "btrfs";
      options = [ "compress=zstd,noatime,subvol=nix" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
